# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: producto_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'producto_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16producto_service.proto\"\x0f\n\rProductoEmpty\"(\n\tProductos\x12\x1b\n\x08producto\x18\x01 \x03(\x0b\x32\t.Producto\"D\n\x08Producto\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x0e\n\x06\x63odigo\x18\x03 \x01(\t\x12\x0c\n\x04\x66oto\x18\x04 \x01(\t2\xf3\x01\n\x0fProductoService\x12%\n\x07\x46indAll\x12\x0e.ProductoEmpty\x1a\n.Productos\x12 \n\x08\x46indById\x12\t.Producto\x1a\t.Producto\x12$\n\x0c\x46indByCodigo\x12\t.Producto\x1a\t.Producto\x12$\n\x0c\x46indByNombre\x12\t.Producto\x1a\t.Producto\x12#\n\x0b\x41\x64\x64Producto\x12\t.Producto\x1a\t.Producto\x12&\n\x0eModifyProducto\x12\t.Producto\x1a\t.ProductoB5\n\x1d\x63om.grpc.grpc_server.servicesB\x14ProductoServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'producto_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035com.grpc.grpc_server.servicesB\024ProductoServiceProto'
  _globals['_PRODUCTOEMPTY']._serialized_start=26
  _globals['_PRODUCTOEMPTY']._serialized_end=41
  _globals['_PRODUCTOS']._serialized_start=43
  _globals['_PRODUCTOS']._serialized_end=83
  _globals['_PRODUCTO']._serialized_start=85
  _globals['_PRODUCTO']._serialized_end=153
  _globals['_PRODUCTOSERVICE']._serialized_start=156
  _globals['_PRODUCTOSERVICE']._serialized_end=399
# @@protoc_insertion_point(module_scope)
