# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import producto_service_pb2 as producto__service__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in producto_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindAll = channel.unary_unary(
                '/ProductoService/FindAll',
                request_serializer=producto__service__pb2.ProductoEmpty.SerializeToString,
                response_deserializer=producto__service__pb2.Productos.FromString,
                _registered_method=True)
        self.FindById = channel.unary_unary(
                '/ProductoService/FindById',
                request_serializer=producto__service__pb2.Producto.SerializeToString,
                response_deserializer=producto__service__pb2.Producto.FromString,
                _registered_method=True)
        self.FindByCodigo = channel.unary_unary(
                '/ProductoService/FindByCodigo',
                request_serializer=producto__service__pb2.Producto.SerializeToString,
                response_deserializer=producto__service__pb2.Producto.FromString,
                _registered_method=True)
        self.FindByNombre = channel.unary_unary(
                '/ProductoService/FindByNombre',
                request_serializer=producto__service__pb2.Producto.SerializeToString,
                response_deserializer=producto__service__pb2.Producto.FromString,
                _registered_method=True)
        self.AddProducto = channel.unary_unary(
                '/ProductoService/AddProducto',
                request_serializer=producto__service__pb2.Producto.SerializeToString,
                response_deserializer=producto__service__pb2.Producto.FromString,
                _registered_method=True)
        self.ModifyProducto = channel.unary_unary(
                '/ProductoService/ModifyProducto',
                request_serializer=producto__service__pb2.Producto.SerializeToString,
                response_deserializer=producto__service__pb2.Producto.FromString,
                _registered_method=True)


class ProductoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FindAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindByCodigo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindByNombre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindAll': grpc.unary_unary_rpc_method_handler(
                    servicer.FindAll,
                    request_deserializer=producto__service__pb2.ProductoEmpty.FromString,
                    response_serializer=producto__service__pb2.Productos.SerializeToString,
            ),
            'FindById': grpc.unary_unary_rpc_method_handler(
                    servicer.FindById,
                    request_deserializer=producto__service__pb2.Producto.FromString,
                    response_serializer=producto__service__pb2.Producto.SerializeToString,
            ),
            'FindByCodigo': grpc.unary_unary_rpc_method_handler(
                    servicer.FindByCodigo,
                    request_deserializer=producto__service__pb2.Producto.FromString,
                    response_serializer=producto__service__pb2.Producto.SerializeToString,
            ),
            'FindByNombre': grpc.unary_unary_rpc_method_handler(
                    servicer.FindByNombre,
                    request_deserializer=producto__service__pb2.Producto.FromString,
                    response_serializer=producto__service__pb2.Producto.SerializeToString,
            ),
            'AddProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.AddProducto,
                    request_deserializer=producto__service__pb2.Producto.FromString,
                    response_serializer=producto__service__pb2.Producto.SerializeToString,
            ),
            'ModifyProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyProducto,
                    request_deserializer=producto__service__pb2.Producto.FromString,
                    response_serializer=producto__service__pb2.Producto.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ProductoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ProductoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FindAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProductoService/FindAll',
            producto__service__pb2.ProductoEmpty.SerializeToString,
            producto__service__pb2.Productos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProductoService/FindById',
            producto__service__pb2.Producto.SerializeToString,
            producto__service__pb2.Producto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindByCodigo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProductoService/FindByCodigo',
            producto__service__pb2.Producto.SerializeToString,
            producto__service__pb2.Producto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindByNombre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProductoService/FindByNombre',
            producto__service__pb2.Producto.SerializeToString,
            producto__service__pb2.Producto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProductoService/AddProducto',
            producto__service__pb2.Producto.SerializeToString,
            producto__service__pb2.Producto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModifyProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProductoService/ModifyProducto',
            producto__service__pb2.Producto.SerializeToString,
            producto__service__pb2.Producto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
