# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: login.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'login.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blogin.proto\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\":\n\rLoginResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x32\x36\n\x0cLoginService\x12&\n\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponseB2\n\x1d\x63om.grpc.grpc_server.servicesB\x11LoginServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'login_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035com.grpc.grpc_server.servicesB\021LoginServiceProto'
  _globals['_LOGINREQUEST']._serialized_start=15
  _globals['_LOGINREQUEST']._serialized_end=65
  _globals['_LOGINRESPONSE']._serialized_start=67
  _globals['_LOGINRESPONSE']._serialized_end=125
  _globals['_LOGINSERVICE']._serialized_start=127
  _globals['_LOGINSERVICE']._serialized_end=181
# @@protoc_insertion_point(module_scope)
