# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tienda_pb2 as tienda__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x1a\x0ctienda.proto\"\x07\n\x05\x45mpty\"\x1c\n\x05Users\x12\x13\n\x04user\x18\x01 \x03(\x0b\x32\x05.User\"\x92\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x17\n\x06tienda\x18\x04 \x01(\x0b\x32\x07.Tienda\x12\x0e\n\x06nombre\x18\x05 \x01(\t\x12\x10\n\x08\x61pellido\x18\x06 \x01(\t\x12\x12\n\nhabilitado\x18\x07 \x01(\x08\x12\x0b\n\x03rol\x18\x08 \x01(\t2\xd8\x01\n\x0bUserService\x12\x19\n\x07\x46indAll\x12\x06.Empty\x1a\x06.Users\x12\x18\n\x08\x46indById\x12\x05.User\x1a\x05.User\x12\x17\n\x07\x41\x64\x64User\x12\x05.User\x1a\x05.User\x12\x1a\n\nModifyUser\x12\x05.User\x1a\x05.User\x12\x1e\n\x0e\x46indByUsername\x12\x05.User\x1a\x05.User\x12\"\n\x0f\x46indAllByTienda\x12\x07.Tienda\x1a\x06.Users\x12\x1b\n\x0b\x44isableUser\x12\x05.User\x1a\x05.UserB1\n\x1d\x63om.grpc.grpc_server.servicesB\x10UserServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035com.grpc.grpc_server.servicesB\020UserServiceProto'
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_USERS']._serialized_start=37
  _globals['_USERS']._serialized_end=65
  _globals['_USER']._serialized_start=68
  _globals['_USER']._serialized_end=214
  _globals['_USERSERVICE']._serialized_start=217
  _globals['_USERSERVICE']._serialized_end=433
# @@protoc_insertion_point(module_scope)
